version: '3'
services:

  node:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app:/home/node/app
    ports:
      - "8081:8081"
    command: "npm start"
    links:
      - db
#      - geoserver

  db:
    image: "mdillon/postgis"
    environment:
      POSTGRES_USER: mapserver
      POSTGRES_PASSWORD: mapserver
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

#  geoserver:
#    image: "geonode/geoserver"
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./maps:/geoserver_data/data
#    links:
#      - db

#  mapserver:
#    image: "camptocamp/mapserver"
#    environment:
#      MS_DEBUGLEVEL: 5
#    ports:
#      - "8380:8000"
#    volumes:
#      - ./maps:/etc/mapserver/
#    links:
#      - db

